# API sürümü ve kaynak tipi. Ingress için bu standarttır.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Ingress objesinin küme içindeki adı
  name: my-ingress
spec:
  # --- KRİTİK EKLENTİ ---
  # 'nginx' controller'ına bu kuralları yönetmesi gerektiğini söyler.
  ingressClassName: nginx
  
  rules:
  # 1. Kural: Frontend (Arayüz)
  # Tarayıcı 'http://todo.rojhat.ince' adresine gittiğinde...
  - host: todo.rojhat.ince
    http:
      paths:
      # Gelen yol '/' (ana sayfa) ise...
      - path: /
        pathType: Prefix
        backend:
          service:
            # ...trafiği 'frontend' isimli Servise yönlendir.
            name: frontend
            port:
              # 'frontend' Servisinin 3000 numaralı portuna.
              number: 3000
  
  # 2. Kural: Backend (API)
  # Tarayıcı 'http://backend.rojhat.ince' adresine gittiğinde...
  - host: backend.rojhat.ince
    http:
      paths:
      # Gelen yol '/' ise...
      - path: /
        pathType: Prefix
        backend:
          service:
            # ...trafiği 'backend' isimli Servise yönlendir.
            name: backend
            port:
              # --- DÜZELTME (Sizin isteğinize göre) ---
              # 'backend' Servisinin 5000 numaralı portuna.
              number: 5000